apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: 'https://github.com/pengchao2022/eks-gitlab-app.git' 
    targetRevision: HEAD
    path: apps/gitlab
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    
      - ServerSideApply=true    