# 注意：因为使用了 dependencies，所有配置必须放在 gitlab: 之下！
gitlab:
  
  # 1. 🔑 彻底禁用升级检查（这回肯定生效了）
  upgradeCheck:
    enabled: false

  # 2. 全局基础配置
  global:
    hosts:
      domain: awsmpc.asia
    
    persistence:
      storageClass: gp3

    ingress:
      configureCertmanager: false
      provider: aws
      class: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/group.name: monitoring-group

  # 3. 禁用内置的证书与网关组件
  certmanager:
    install: false

  nginx-ingress:
    enabled: false

  # 4. 可选配置：内置工具链
  gitlab-runner:
    install: true